# Matrix

In [1]:
matrix1<-matrix(c(11, 13, 15, 12, 14, 16),nrow =2, ncol =3, byrow = TRUE)  
matrix1  

[,1] [,2] [,3]
[1,] 11   13   15  
[2,] 12   14   16

In [3]:
# Defining the column and row names.  
row_names = c("row1", "row2", "row3", "row4")  
col_names = c("col1", "col2", "col3")  
#Creating matrix   
R <- matrix(c(5:16), nrow = 4, byrow = TRUE, dimnames = list(row_names, col_names))  
print(R)  
  
#Accessing element present on 3rd row and 2nd column  
print(R[3,2])  
  
#Accessing element present in 3rd row  
print(R[3,])  
  
#Accessing element present in 2nd column  
print(R[,2])  

     col1 col2 col3
row1    5    6    7
row2    8    9   10
row3   11   12   13
row4   14   15   16
[1] 12
col1 col2 col3 
  11   12   13 
row1 row2 row3 row4 
   6    9   12   15 


In [4]:
# Defining the column and row names.  
row_names = c("row1", "row2", "row3", "row4")  
ccol_names = c("col1", "col2", "col3")  
  
R <- matrix(c(5:16), nrow = 4, byrow = TRUE, dimnames = list(row_names, col_names))  
print(R)  
  
#Assigning value 20 to the element at 3d roe and 2nd column  
R[3,2]<-20  
print(R)  

     col1 col2 col3
row1    5    6    7
row2    8    9   10
row3   11   12   13
row4   14   15   16
     col1 col2 col3
row1    5    6    7
row2    8    9   10
row3   11   20   13
row4   14   15   16


In [5]:
# Defining the column and row names.  
row_names = c("row1", "row2", "row3", "row4")  
ccol_names = c("col1", "col2", "col3")  
  
R <- matrix(c(5:16), nrow = 4, byrow = TRUE, dimnames = list(row_names, col_names))  
print(R)  
  
#Adding row  
rbind(R,c(17,18,19))  
  
#Adding column  
cbind(R,c(17,18,19,20))  
  
#transpose of the matrix using the t() function:  
t(R)  
  
#Modifying the dimension of the matrix using the dim() function  
dim(R)<-c(1,12)  
print(R)  

     col1 col2 col3
row1    5    6    7
row2    8    9   10
row3   11   12   13
row4   14   15   16


col1 col2 col3
row1  5    6    7  
row2  8    9   10  
row3 11   12   13  
row4 14   15   16  
     17   18   19

col1 col2 col3   
row1  5    6    7   17
row2  8    9   10   18
row3 11   12   13   19
row4 14   15   16   20

row1 row2 row3 row4
col1 5     8   11   14  
col2 6     9   12   15  
col3 7    10   13   16

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
[1,]    5    8   11   14    6    9   12   15    7    10    13    16


In [6]:
R <- matrix(c(5:16), nrow = 4,ncol=3)  
S <- matrix(c(1:12), nrow = 4,ncol=3)  
  
#Addition  
sum<-R+S  
print(sum)  
  
#Subtraction  
sub<-R-S  
print(sub)  
  
#Multiplication  
mul<-R*S  
print(mul)  
  
#Multiplication by constant  
mul1<-R*12  
print(mul1)  
  
#Division  
div<-R/S  
print(div)  

     [,1] [,2] [,3]
[1,]    6   14   22
[2,]    8   16   24
[3,]   10   18   26
[4,]   12   20   28
     [,1] [,2] [,3]
[1,]    4    4    4
[2,]    4    4    4
[3,]    4    4    4
[4,]    4    4    4
     [,1] [,2] [,3]
[1,]    5   45  117
[2,]   12   60  140
[3,]   21   77  165
[4,]   32   96  192
     [,1] [,2] [,3]
[1,]   60  108  156
[2,]   72  120  168
[3,]   84  132  180
[4,]   96  144  192
         [,1]     [,2]     [,3]
[1,] 5.000000 1.800000 1.444444
[2,] 3.000000 1.666667 1.400000
[3,] 2.333333 1.571429 1.363636
[4,] 2.000000 1.500000 1.333333
